version: '3.4'

services:
    db:
        image: mariadb:11
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/:ro
        environment:
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password
          - MYSQL_DATABASE=f1datadb
          - MYSQL_ROOT_PASSWORD=supersecretpwd
        ports:
            - '3306:3306'
        networks:
            back:
                ipv4_address: 10.5.0.5
    check-db-started:
        image: jwilder/dockerize:latest
        depends_on:
            - db
        command: 'dockerize -wait=tcp://10.5.0.5:3306 -timeout 60s'
        networks:
            - back
    reverse_proxy:
        build:
            context: ./ReverseProxy
        image: ${DOCKER_REGISTRY-}reverseproxy
        ports:
            - "5000:80"
            - "5001:5001"
        networks:
            - overlay
        depends_on:
            - frontend
    frontend:
        image: ${DOCKER_REGISTRY-}frontend
        build:
            context: ./ClientApp
        networks:
            - overlay
        depends_on:
            - backend
    backend:
        image: ${DOCKER_REGISTRY-}backend
        build:
            context: .
        networks:
            - overlay
            - back
        depends_on:
            check-db-started:
                condition: service_completed_successfully

 
networks:
    overlay:
    back:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1
   