# This workflow will build a Java project with Gradle whenever you push a commit to the repository.
# It will also build the client app.

name: F1 data application build

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: '2'

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: 'gradle'

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build -x test

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd ClientApp
    - run: npm install
    - run: npm run build --if-present